### ISSUE TITLE
Connect eoapi-k8s STAC FastAPI to External PostgreSQL Database

### ISSUE THREAD

**Issue by MathewNWSH** [developmentseed/eoapi-k8s#133]
### Description

Hello everyone, I have recently returned to the topic of deploying pgstack and stac-fast API on Kubernetes (my deployment using Docker Compose can no longer handle the storage needs :).

And here is where I have a problem: many thanks for creating the cloud-native PostgreSQL operator, thanks to it eoapi-k8s is really an amazing tool for working with the cloud in every regard, but we have set up our own bare-metal server dedicated to the PostgreSQL database. **The server has been configured for HA (master and synchronizing read-only slaves), so I would like to use this database. This means that, I would like to keep it on a different cluster**. Can this be done? i.e., is it enough in the YAML to add:
```
db:
  settings:
    secrets:
      PGUSER: "username"
      POSTGRES_USER: "username"
      PGPASSWORD: "password"
      POSTGRES_PASSWORD: "password"
      PGHOST: "bare metal load balancer floating IP"
```
Thanks for the response and the developers' work on eoapi.

### Labels

- [x] enhancement
- [X] discussion
- [X] help wanted
