### ISSUE TITLE
raster / titiler : Mixed content error while working with a reverse proxy

### ISSUE THREAD

**Issue by cmarquezrusso** [developmentseed/eoapi-k8s#159]
#### Problem description
I'm experiencing an issue with my application that is deployed on Kubernetes using an Nginx Ingress Controller, Cert Manager for TLS, and External DNS. The application fails to load over HTTPS due to mixed content errors, as it's attempting to fetch HTTP resources.

I've attached a diagram for your reference.
![error drawio](https://github.com/user-attachments/assets/0d237a15-4d01-456a-8eed-514daf291ee3)

Steps to Reproduce:

- Attempt to load the application in a browser via the HTTPS URL.
- The website will not load, even when the certificate is valid
- Observe the console for mixed content errors indicating that HTTP resources are being fetched.

Error
```
Blocked loading mixed active content “http://eoapi-nginx.something.com/raster/searches/a032658c3431ccc83f196ccea9b0146d/WebMercatorQuad/tilejson.json?assets=data&asset_bidx=data%7C1&rescale=0%2C3000&items_limit=100&time_limit=60&colormap_name=greens”
```

Looking at the javascript function, I can see the following 
```javascript
fetch('http://eoapi-nginx.something.com/raster/searches/a032658c3431ccc83f196ccea9b0146d/WebMercatorQuad/tilejson.json?assets=data&asset_bidx=data%7C1&rescale=0%2C3000&items_limit=100&time_limit=60&colormap_name=greens')
  .then(res => {
    if (res.ok) return res.json()
[...]
```

Workaround:
Removing the protocol from the fetch function:
```javascript
fetch('//eoapi-nginx.something.com'[...]
```

#### Expected Output

The map must load

#### Environment Information
k8s 1.30
eoapi:0.4.17

Ingress Annotations:
```yaml
ingress:
  enabled: true
  className: "nginx"
  host: "eoapi-nginx.something.com"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
      proxy_set_header x-forwarded-host $http_x_forwarded_host;
      proxy_set_header x-forwarded-proto $http_x_forwarded_proto;
      proxy_set_header x-forwarded-scheme $http_x_forwarded_scheme;
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns01"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
  tls:
    enabled: true
    secretName: eoapi-tls
```
